language: node_js

node_js:
  - "10"

dist: trusty

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN

cache:
  directories:
    - "node_modules"

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    # no test because of an issue with jest caching on Travis CI
    # - stage: test
    #   script: npm test
    - stage: sonar
      script: sonar-scanner
